version: '3.8'

services:
  bot:
    build: ../dev-pilot-ai-backend  # Путь к dev-pilot-ai
    ports:
      - "8080:8080"
    restart: always  # Перезапуск при сбоях

  postgres:
    image: postgres
    restart: always  # Перезапуск при сбоях
    environment:
      POSTGRES_DB: DevPilotAI_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data  # Сохраняем данные в volume

volumes:
  data-volume:
